### ISSUE TITLE
Error: Cannot find module '/usr/local/lib/node_modules/gulp/node_modules/v8flags/3.28.71.19.flags.json'

### ISSUE THREAD

**Issue by dunphyben** [xtine/firestarter#1]
`npm install` works just fine, but when i run `gulp` i get the following error:

```
Benjamins-MBP:firestarter ben$ gulp
module.js:338
    throw err;
          ^
Error: Cannot find module '/usr/local/lib/node_modules/gulp/node_modules/v8flags/3.28.71.19.flags.json'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/gulp/bin/gulp.js:25:22)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
```

**Comment by xtine** [comment]
@dunphyben might have to install gulp globally, with the -g flag. See: https://github.com/GoogleChrome/ioweb2015/issues/1372
